# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flicks' do
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

# Pods for Flicks
pod 'AFNetworking', '~> 3.1'
pod 'MBProgressHUD'

end
